languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "François Bertet"
description = "Personal website of François Bertet. Freelance Senior DevOps Engineer"
dateFormat = "2 January 2006"

[params]
  # mainSections = ["section1", "section2"]

[author]
   name = "François Bertet"
   image = "img/author.jpg"
   headline = "Freelance Senior DevOps Engineer"
   bio = "Freelance Senior DevOps Engineer"
   links = [
     { github = "https://github.com/fbertet" },
     { linkedin = "https://linkedin.com/in/fbertet" },
     { email = "mailto:fr.bertet@gmail.com" }
   ]
